/**
 * Stichting (bestuur) — first-class entity introduced in Phase 27 Plan 02.
 *
 * A Stichting groups N schools under a single bestuur. Sales-accountmanagers
 * use this for cross-school planning, bulk-export (Plan 11) and bulk-link
 * (Plan 07). The `usageMix` indicator on the overview card is derived from
 * each school's `currentToolUsage` (filled by Plan 27-05) — until that lands
 * the helper returns `'unknown'`.
 */

import type { SchoolRecord } from '@/db/types';

/**
 * Authoritative Stichting record shape. Mirrored 1-on-1 between Supabase
 * (`stichtingen` table, Migration 014) and Dexie v3 (`stichtingen` store).
 *
 * Dates are kept as ISO strings to match the rest of the persistence layer
 * (see `SchoolRecord` — strings, not `Date` objects).
 */
export interface StichtingRecord {
  /** UUID generated by Supabase (`gen_random_uuid()`). */
  id: string;
  /** Owning team (RLS scope). */
  teamId: string;
  /** Stichting name (e.g. "Stichting Voortgezet Onderwijs Amsterdam"). */
  name: string;
  /** Optional region label — defaults to '' if not provided. */
  region: string;
  /** ISO timestamp from Supabase. */
  createdAt: string;
  /** ISO timestamp from Supabase (bumped via `set_updated_at` trigger). */
  updatedAt: string;
  /** UUID of the user who created the row. */
  createdBy?: string;
  /** UUID of the user who last modified the row. */
  updatedBy?: string;
}

/**
 * Aggregated usage mix across all schools linked to a Stichting.
 *
 * - `cito-only`     — every linked school is fully on Cito.
 * - `concurrent-only` — every linked school uses only competitors.
 * - `mixed`         — at least one Cito school and at least one competitor school.
 * - `unknown`       — no linked schools, or the `currentToolUsage` data
 *                     hasn't been collected yet (pre Plan 27-05).
 */
export type UsageMix = 'cito-only' | 'concurrent-only' | 'mixed' | 'unknown';

/** Dutch labels for the usage-mix indicator (UI tooltip + legend). */
export const STICHTING_USAGE_MIX_LABELS: Record<UsageMix, string> = {
  'cito-only': 'Alleen Cito',
  'concurrent-only': 'Alleen concurrent',
  mixed: 'Gemengd',
  unknown: 'Onbekend',
};

/** Tailwind colour tokens for the 3-dot indicator. Grey = unknown. */
export const STICHTING_USAGE_MIX_COLORS: Record<UsageMix, string> = {
  'cito-only': 'bg-green-500',
  'concurrent-only': 'bg-orange-500',
  mixed: 'bg-blue-500',
  unknown: 'bg-neutral-300',
};

/**
 * Derive the usage-mix for a Stichting from its linked schools.
 *
 * Plan 27-05 (R5) flips this from the Plan 27-02 placeholder to real
 * classification based on each school's per-niveau `currentToolUsage`
 * map. Aggregation rules (per Plan 27-05 interfaces-block):
 *
 * - Any per-niveau `'mix'` value, or both Cito- and concurrent-side
 *   values across the corpus → `'mixed'`.
 * - Every recorded value === `'cito'` → `'cito-only'`.
 * - Every recorded value ∈ `{'dia','jij','geen'}` (no Cito anywhere)
 *   → `'concurrent-only'`. (`'geen'` = "nieuwe markt" — treated as
 *   non-Cito side since the school is not on Cito today.)
 * - No recorded values at all (legacy schools / fresh stichting)
 *   → `'unknown'`.
 *
 * @param schools The schools linked to the Stichting. Pass an empty array
 * if the Stichting has no schools yet (also returns `'unknown'`).
 */
export function getStichtingUsageMix(schools: SchoolRecord[]): UsageMix {
  if (!schools || schools.length === 0) return 'unknown';

  let hasCito = false;
  let hasConcurrent = false;
  let hasAnyValue = false;

  for (const school of schools) {
    const usage = school.currentToolUsage;
    if (!usage) continue;
    for (const value of Object.values(usage)) {
      if (!value) continue;
      hasAnyValue = true;
      // Per-niveau 'mix' immediately implies the stichting is mixed —
      // can short-circuit but keep iterating cheap for clarity.
      if (value === 'mix') {
        return 'mixed';
      }
      if (value === 'cito') {
        hasCito = true;
      } else {
        // 'dia' | 'jij' | 'geen' — all non-Cito-side
        hasConcurrent = true;
      }
      if (hasCito && hasConcurrent) {
        return 'mixed';
      }
    }
  }

  if (!hasAnyValue) return 'unknown';
  if (hasCito && !hasConcurrent) return 'cito-only';
  if (hasConcurrent && !hasCito) return 'concurrent-only';
  return 'mixed';
}

/**
 * Error thrown by `deleteStichting` when the Stichting still has linked
 * schools. Cascade-guard per D-04: sales must explicitly unlink schools
 * before the bestuur can be removed (prevents accidental data loss).
 */
export class StichtingCascadeError extends Error {
  readonly stichtingId: string;
  readonly linkedSchoolCount: number;

  constructor(stichtingId: string, linkedSchoolCount: number) {
    const schoolWord = linkedSchoolCount === 1 ? 'school' : 'scholen';
    super(
      `Stichting ${stichtingId} kan niet verwijderd worden: ${linkedSchoolCount} ${schoolWord} nog gekoppeld.`,
    );
    this.name = 'StichtingCascadeError';
    this.stichtingId = stichtingId;
    this.linkedSchoolCount = linkedSchoolCount;
  }
}
